#!/bin/sh
#
# $Id: prtcreate,v 1.1.1.1 2003/08/27 11:43:05 opel Exp $
# (c) 2003 by Martin Opel <martin@obbl-net.de>
#
# May be redistributed and modified under the terms of the GPL
# only usable with CRUX Linux, version 1.0 or higher.
#
# USE AT YOUR OWN RISK
#
# This script creates a Pkgfile in the current working directory with
# all necessary header information fields and an empty build() function.
# The port name is the name of the current working directory.

if [ -f Pkgfile ]; then
	echo "Pkgfile exists!"
	exit 1
fi

NAME=`basename $PWD`

if [ $# -gt 1 ]; then
	echo "usage: $0 [type]"
	exit 1
fi

if [ -e "$HOME/.prtcreaterc" ]; then
	. "$HOME/.prtcreaterc"
fi

if [ "$1" -a -e "$HOME/.prtcreate/$1" ]; then
    cp "$HOME/.prtcreate/$1" Pkgfile
    sed "s/%NAME%/$NAME/" -i Pkgfile
else
    cat <<EOF > Pkgfile
# Description:
# URL:
# Maintainer: $PACKAGER
# Packager: $PACKAGER
# Depends on:

name=`basename $PWD`
version=
release=1
source=()

build() {
	cd \$name-\$version
}
EOF
fi

